baseURL = 'https://velocrush.ch/'
languageCode = 'de-ch'
title = 'Velo Crush'
theme = 'velocrush'
sectionPagesMenu = 'main'

[params]
  tagline = 'Wir lieben Velos! Veloladen und Reparaturwerkstatt.'
  [params.company]
    name = 'Velo Crush'
    legal-form = 'GmbH'
  [params.contact]
    email = 'info@velocrush.ch'
    street = 'Zweierstrasse 56'
    zip = 'CH-8004'
    city = 'ZÃ¼rich'
    phone = '077 242 47 64'
